"""Added collateral item to loans

Revision ID: 00799239488d
Revises: f5ecaeea06d3
Create Date: 2025-02-26 23:21:41.939146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00799239488d'
down_revision = 'f5ecaeea06d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collateral_item', sa.String(length=100), nullable=False))
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('collateral_item')

    # ### end Alembic commands ###
