"""Add current_balance to Loan model

Revision ID: 9d3909452e71
Revises: 00799239488d
Create Date: 2025-02-27 17:32:53.175363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3909452e71'
down_revision = '00799239488d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('current_balance')
        batch_op.drop_column('opening_balance')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=150), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('loyalty_points', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('loans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('collateral_item', sa.VARCHAR(length=100), nullable=False),
    sa.Column('loan_amount', sa.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_loans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_amount', sa.FLOAT(), nullable=True),
    sa.Column('collateral', sa.VARCHAR(length=100), nullable=True),
    sa.Column('loan_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('settlement_date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_loan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_amount', sa.FLOAT(), nullable=True),
    sa.Column('collateral', sa.VARCHAR(length=100), nullable=True),
    sa.Column('loan_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('settlement_date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
