"""Add settled_date to loan model

Revision ID: 16f7adde826c
Revises: f6ba2fab1543
Create Date: 2025-02-27 18:54:01.770499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f7adde826c'
down_revision = 'f6ba2fab1543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settled_date', sa.Date(), nullable=True))
        batch_op.drop_column('current_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('settled_date')

    # ### end Alembic commands ###
