"""Add back current_balance to loan model

Revision ID: f1d88c2e012d
Revises: 16f7adde826c
Create Date: 2025-02-27 18:57:01.121385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d88c2e012d'
down_revision = '16f7adde826c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('current_balance')

    # ### end Alembic commands ###
